### ISSUE TITLE
Deleting a PV does not result in a deletion of the associated resources

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-csi/external-attacher#124]
Actual behavior:

* Issuing `Delete` on a PV results in that PV vanishing but the volume at the cloud provider staying. The volume at the cloud provider only gets deleted when deleting the `PVC`

Expected behavior:

* After a PV is deleted from my cluster, all associated resources at the cloud provider are gone

**Comment by alvaroaleman** [comment]
This can be reproduced by using any CSI driver that uses the external attacher (I used [this one](https://github.com/hetznercloud/csi-driver) and then either:

* Creating a storegaclass with a `ReclaimPolicy: Delete` 
* Creating a PVC with that storageclass
* Deleting the associated PV after it was created
* Deleting the PVC because otherwise the PV won't go

=> PVC and PV are gone, volume at cloud provider is still present

or:

* Creating a storageclass with a `ReclaimPolicy: Retain`
* Creating a PVC with that storageclass
* Deleting  the PVC
* Deleting the PV

=> PVC and PV are gone, volume at cloud provider is still present

This means that for a  cleanup of 
* volumes with `Storageclass: Delete` only the PVC may be deleted, the PV must not be deleted, else the Volume will stay
* volumes with `Storageclass: Retain` is impossible

**Comment by davidz627** [comment]
> * Creating a storageclass with a `ReclaimPolicy: Retain`
> * Creating a PVC with that storageclass
> * Deleting  the PVC
> * Deleting the PV
This is working as intended: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain

> * Creating a storegaclass with a `ReclaimPolicy: Delete`
> * Creating a PVC with that storageclass
> * Deleting the associated PV after it was created
> * Deleting the PVC because otherwise the PV won't go
The workflow for deleting a dynamically provisioned volume is to just remove the PVC. The PV and volume will get cleaned up automatically. The reason the PV "wont go" is because of the [finalizer](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#storage-object-in-use-protection) that is meant to prevent you from deleting PV's that are still bound to PVC's. To resolve this just delete the PVC and don't touch the PV.

However, I would expect that the volume should be deleted in the first set of reproduction steps you gave so maybe that is a bug. Could you refile just that piece in `kubernetes/kubernetes` or `kubernetes-csi/external-provisioner`.
