### ISSUE TITLE
Different permissions between attacher roles in example and k8s

### ISSUE THREAD

**Issue by verult** [kubernetes-csi/external-attacher#151]
The RBAC permissions listed in the attacher role in the example are different from those bundled into k8s:
https://github.com/kubernetes/kubernetes/blob/4e397d971a72f5bc6dbffbacca7297f17e17c572/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L471

Should they be different? Should most users just use the built-in role?

**Comment by pohly** [comment]
The built-in roles are obsolete. Building RBAC rules for an external component with an independent release cycle into Kubernetes core was a conceptual dead-end. I think we (I?) added a deprecation note for them in an older Kubernetes release; it might be okay to remove them  now.

Whoever puts together a CSI driver deployment (usually the storage vendor) must ensure that the deployment has its own matching RBAC rules. This may imply editing the upstream RBAC rules, because they depend on how the component is used in the deployment. For example: https://github.com/kubernetes-csi/external-provisioner/blob/967b7a310b197d3294b52af84a195b45b9a0e1d2/deploy/kubernetes/rbac.yaml#L24-L28

**Comment by verult** [comment]
@pohly could you check when the deprecation note was added? Is there a tracking issue for removing them? If not and it hasn't been a year yet, we could use this issue for tracking

**Comment by verult** [comment]
https://github.com/kubernetes/kubernetes/issues/78739
