### ISSUE TITLE
Attacher should use storage.k8s.io/v1beta1 API instead of v1alpha1

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-csi/external-attacher#39]
Currently, attacher uses `storage.k8s.io/v1alpha1` API to talk to Kubernetes and work with `VOlumeAttachment` objects. `v1alpha1` needs to be explicitly enabled by cluster admins.

We should move to `v1beta1`, which is enabled by default.

**Comment by pohly** [comment]
Is this issue only about `k8s.io/api/storage/v1alpha1` or also about `k8s.io/client-go/informers/storage/v1alpha1` and `k8s.io/client-go/listers/storage/v1beta1`?

`k8s.io/api/storage` seems to be a simple search/replace, but `k8s.io/client-go` is a bit more involved, because the newer API deals with StorageClass instances, not VolumeAttachment.

**Comment by pohly** [comment]
Probably all of them, because `vendor/k8s.io/client-go/listers/storage/v1alpha1/volumeattachment.go` uses the `k8s.io/api/storage/v1alpha1` API...

The latest API for `k8s.io/client-go` is `v1`, not `v1beta1`. Same for `vendor/k8s.io/api/storage`. Shouldn't we use `v1` then instead of `v1beta1`?

**Comment by saad-ali** [comment]
@sbezverk has volunteered to work on this.

**Comment by jsafrane** [comment]
Fixed by #40
